#!/usr/bin/env bash
export LC_ALL=C
set -euo pipefail

IMAGE_NAME="${IMAGE_NAME:-bitcoin-build}"
BITCOIN_SRC="${BITCOIN_SRC:-"../bitcoin"}"
cd "$BITCOIN_SRC"
bitcoin_src="$(pwd)"

BDB_PREFIX="${BDB_PREFIX:-"$bitcoin_src/db4"}"

DOCKER_ARGS=${DOCKER_ARGS:-""}

docker run $DOCKER_ARGS --rm -it --init \
  -u "$(id -u):$(id -g)"  \
  -v "$(pwd):$(pwd)" -w "$(pwd)" \
  -v "$HOME/.bitcoin:$HOME/.bitcoin" \
  -e BDB_PREFIX="$BDB_PREFIX" \
  "${IMAGE_NAME}" "$@"
